[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "aiotieba"
description = "Asynchronous I/O Client/Reviewer for Baidu Tieba"
requires-python = ">=3.9"
authors = [{ name = "Starry-OvO", email = "starry.qvq@gmail.com" }]
keywords = ["tieba", "crawler", "spider"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: AsyncIO",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: The Unlicense (Unlicense)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Internet :: WWW/HTTP :: Session",
]
urls = { Homepage = "https://github.com/Starry-OvO/Tieba-Manager" }
dependencies = [
    "aiodns>=3.0.0",
    "aiohttp>=3.8.0",
    "aiomysql>=0.1.0",
    "beautifulsoup4>=4.0.0",
    "Brotli>=1.0.0",
    "lxml>=4.0.0",
    "opencv-contrib-python-headless>=4.6.0.66",
    "pycryptodome>=3.0.0",
    "tomli>=2.0.0",
]
dynamic = ["version", "readme"]

[tool.setuptools.packages.find]
where = ["aiotieba"]

[tool.setuptools.package-data]
"aiotieba.config_example" = ["*.toml"]

[tool.setuptools.dynamic]
version = { attr = "aiotieba.__version__" }
readme = { file = "README.md" }

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py39', 'py310']
include = '\.pyi?$'

[tool.pytest.ini_options]
minversion = "6.0"
required_plugins = "pytest-asyncio"
addopts = "-q"
asyncio_mode = "strict"
