[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py39', 'py310']
include = '\.pyi?$'

[tool.pytest.ini_options]
minversion = "6.0"
required_plugins = "pytest-asyncio"
addopts = "-q"
asyncio_mode = "strict"
