listener_key: listener # 在这里填用于监听at信息的账号的BDUSS_key
configs:
  -
    fname: lol半价 # 在这里填贴吧名
    admin_key: default # 在这里填用于在该吧行使吧务权限的账号的BDUSS_key
    speaker_key: default # 在这里填用于在该吧发送回复的账号的BDUSS_key
  -
    fname: asoul # 在这里填另一个贴吧名
    admin_key: default # 在这里填用于在该吧行使吧务权限的账号的BDUSS_key
    speaker_key: default # 在这里填用于在该吧发送回复的账号的BDUSS_key
