name: Basic Test

on:
  push:
    branches: [ develop ]
    paths:
      - 'aiotieba/**'
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    environment: develop

    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Restore pip Cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Prepare config
      shell: bash
      run: |
        mv .github/test/test_all.py .
        mkdir config
        gpg --quiet --batch --yes --decrypt --passphrase=${{ secrets.PASSPHRASE }} --output aiotieba.toml .github/test/aiotieba.toml.gpg

    - name: Run test
      run: python test_all.py
