name: Python Basic Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    environment: develop

    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Decrypt config
        run: ./.github/test/prepare.sh
        env:
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

    - name: Run test
      run: |
        python test_all.py
